#kubectl run n1 --image=nginx --port=80
#kubectl expose pod n1 --name=n1svc --port=80 --target-port=80 --type=NodePort
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: Pod
metadata:
  name: n1
  labels:
    app: nginx
  namespace: dev
spec:
  containers:
  - name: nginx
    image: "nginx:latest"
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: n1svc
  namespace: dev
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort